### ISSUE TITLE
<!DOCTYPE html>-tag destroys layout

### ISSUE THREAD

**Issue by MrTomRod** [ihh/tree-align-view#24]
Thanks for making this cool, simple and versatile tool!

I want to embed it into a website but noticed a bug: The standard declaration of `<!DOCTYPE html>` destroys the layout!

This is how to reproduce this: Simply replace `<html>` with `<!DOCTYPE html>` in `demo.html`.

That's what it looks like (tested in Firefox and Chrome):

![image](https://user-images.githubusercontent.com/40867365/89643083-4cf49900-d8b5-11ea-8910-ba08a97e616a.png)

**Comment by ihh** [comment]
Thanks for your interest @MrTomRod and for the bug report!

This repo has actually been replaced by a more modern React component, which is available here: https://github.com/ihh/abrowse

The React version is functionally equivalent, but does not have this DOCTYPE bug, and will be the version that is maintained going forward.

All best,
Ian
